name: IPTV Restream

on:
  workflow_dispatch: # solo ejecución manual

jobs:
  restream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Instalar ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Leer link y generar M3U8 restream
        run: |
          LINK=$(cat origen.txt)
          mkdir -p playlist
          ffmpeg -i "$LINK" \
          -c:v copy -c:a aac -b:a 128k \
          -f hls -hls_time 5 -hls_list_size 0 -hls_flags independent_segments playlist/restream.m3u8

      - name: Commit y push resultado
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add playlist/restream.m3u8
          git commit -m "Actualizar restream.m3u8 [skip ci]" || echo "Sin cambios"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
